# Generated by Django 5.2 on 2025-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSMCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('S', models.FloatField()),
                ('K', models.FloatField()),
                ('r', models.FloatField()),
                ('t', models.FloatField()),
                ('q', models.FloatField()),
                ('sigma', models.FloatField()),
                ('call', models.FloatField()),
                ('put', models.FloatField()),
            ],
        ),
    ]
